language: go
go:
  - 1.3
  - tip
before_install:
  - sudo apt-get update
install:
  - sudo apt-get install ffmpeg libtagc0-dev
before_script:
  - go get ./...
script:
  - go build ./...
  - go test -v ./...
