language: go
go:
  - 1.1
  - 1.2
  - 1.3
before_install:
  - sudo apt-get update
install:
  - sudo apt-get install ffmpeg libtagc0-dev
before_script:
  - go get ./...
script:
  - make
  - ./bin/wavepipe -test
  - make test
