language: go
go:
  - 1.1
  - 1.2
before_install:
  - sudo apt-get update
install:
  - sudo apt-get install libtagc0-dev
before_script:
  - go get github.com/mdlayher/goset
  - go get github.com/wtolson/go-taglib
script:
  - make
  - make test
  - ./bin/wavepipe -test .
