language: go
go:
  - 1.1
  - 1.2
before_install:
  - sudo apt-get update
install:
  - sudo apt-get install libtagc0-dev php5-cli php5-json
before_script:
  - go get code.google.com/p/go.crypto/bcrypt
  - go get code.google.com/p/go.crypto/pbkdf2
  - go get github.com/go-martini/martini
  - go get github.com/jmoiron/sqlx
  - go get github.com/martini-contrib/gzip
  - go get github.com/martini-contrib/render
  - go get github.com/mattn/go-sqlite3
  - go get github.com/mdlayher/goset
  - go get github.com/romanoff/fsmonitor
  - go get github.com/willf/bloom
  - go get github.com/wtolson/go-taglib
script:
  - make
  - ./bin/wavepipe -test &
  - sleep 5
  - php ./res/wavepipe_test.php localhost:8080
  - sleep 30
  - make test
